<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSearchTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('searches', function (Blueprint $table) {
            $table->increments('id');
            $table->bigInteger('code');
            $table->text('url');
            $table->text('creator');
            $table->text('created_t');
            $table->text('created_datetime');
            $table->text('last_modified_t');
            $table->text('last_modified_datetime');
            $table->text('product_name');
            $table->text('generic_name');
            $table->text('quantity');
            $table->text('packaging');
            $table->text('packaging_tags');
            $table->text('brands');
            $table->text('brands_tags');
            $table->text('categories');
            $table->text('categories_tags');
            $table->text('categories_en');
            $table->text('origins');
            $table->text('origins_tags');
            $table->text('manufacturing_places');
            $table->text('manufacturing_places_tags');
            $table->text('labels');
            $table->text('labels_tags');
            $table->text('labels_en');
            $table->text('emb_codes');
            $table->text('emb_codes_tags');
            $table->text('first_packaging_code_geo');
            $table->text('cities');
            $table->text('cities_tags');
            $table->text('purchase_places');
            $table->text('stores');
            $table->text('countries');
            $table->text('countries_tags');
            $table->text('countries_en');
            $table->text('ingredients_text');
            $table->text('allergens');
            $table->text('allergens_en');
            $table->text('traces');
            $table->text('traces_tags');
            $table->text('traces_en');
            $table->text('serving_size');
            $table->text('no_nutriments');
            $table->text('additives_n');
            $table->text('additives');
            $table->text('additives_tags');
            $table->text('additives_en');
            $table->text('ingredients_from_palm_oil_n');
            $table->text('ingredients_from_palm_oil');
            $table->text('ingredients_from_palm_oil_tags');
            $table->text('ingredients_that_may_be_from_palm_oil_n');
            $table->text('ingredients_that_may_be_from_palm_oil');
            $table->text('ingredients_that_may_be_from_palm_oil_tags');
            $table->text('nutrition_grade_uk');
            $table->text('nutrition_grade_fr');
            $table->text('pnns_groups_1');
            $table->text('pnns_groups_2');
            $table->text('states');
            $table->text('states_tags');
            $table->text('states_en');
            $table->text('main_category');
            $table->text('main_category_en');
            $table->text('image_url');
            $table->text('image_small_url');
            $table->text('energy_100g');
            $table->text('energy_from_fat_100g');
            $table->text('fat_100g');
            $table->text('saturated_fat_100g');
            $table->text('NAME_');
            $table->text('Column0');
            $table->text('Column1');
            $table->text('Column2');
            $table->text('Column3');
            $table->text('Column4');
            $table->text('Column5');
            $table->text('Column6');
            $table->text('Column7');
            $table->text('Column8');
            $table->text('Column9');
            $table->text('Column10');
            $table->text('Column11');
            $table->text('Column12');
            $table->text('monounsaturated_fat_100g');
            $table->text('polyunsaturated_fat_100g');
            $table->text('omega_3_fat_100g');
            $table->text('Column13');
            $table->text('Column14');
            $table->text('Column15');
            $table->text('omega_6_fat_100g');
            $table->text('Column16');
            $table->text('Column17');
            $table->text('Column18');
            $table->text('Column19');
            $table->text('omega_9_fat_100g');
            $table->text('Column20');
            $table->text('Column21');
            $table->text('Column22');
            $table->text('Column23');
            $table->text('Column24');
            $table->text('Column25');
            $table->text('trans_fat_100g');
            $table->text('cholesterol_100g');
            $table->text('carbohydrates_100g');
            $table->text('sugars_100g');
            $table->text('Column26');
            $table->text('Column27');
            $table->text('Column28');
            $table->text('Column29');
            $table->text('Column30');
            $table->text('Column31');
            $table->text('starch_100g');
            $table->text('polyols_100g');
            $table->text('fiber_100g');
            $table->text('proteins_100g');
            $table->text('casein_100g');
            $table->text('serum_proteins_100g');
            $table->text('nucleotides_100g');
            $table->text('salt_100g');
            $table->text('sodium_100g');
            $table->text('alcohol_100g');
            $table->text('vitamin_a_100g');
            $table->text('beta_carotene_100g');
            $table->text('vitamin_d_100g');
            $table->text('vitamin_e_100g');
            $table->text('vitamin_k_100g');
            $table->text('vitamin_c_100g');
            $table->text('vitamin_b1_100g');
            $table->text('vitamin_b2_100g');
            $table->text('vitamin_pp_100g');
            $table->text('vitamin_b6_100g');
            $table->text('vitamin_b9_100g');
            $table->text('folates_100g');
            $table->text('vitamin_b12_100g');
            $table->text('biotin_100g');
            $table->text('pantothenic_acid_100g');
            $table->text('silica_100g');
            $table->text('bicarbonate_100g');
            $table->text('potassium_100g');
            $table->text('chloride_100g');
            $table->text('calcium_100g');
            $table->text('phosphorus_100g');
            $table->text('iron_100g');
            $table->text('magnesium_100g');
            $table->text('zinc_100g');
            $table->text('copper_100g');
            $table->text('manganese_100g');
            $table->text('fluoride_100g');
            $table->text('selenium_100g');
            $table->text('chromium_100g');
            $table->text('molybdenum_100g');
            $table->text('iodine_100g');
            $table->text('caffeine_100g');
            $table->text('taurine_100g');
            $table->text('ph_100g');
            $table->text('fruits_vegetables_nuts_100g');
            $table->text('collagen_meat_protein_ratio_100g');
            $table->text('cocoa_100g');
            $table->text('chlorophyl_100g');
            $table->text('carbon_footprint_100g');
            $table->text('nutrition_score_fr_100g');
            $table->text('nutrition_score_uk_100g');
            $table->text('glycemic_index_100g');
            $table->text('water_hardness_100g');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('searches');
    }
}
